// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for windows - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzG_UJs1VHbDOTJKRvMrFRqVNK8MCuFUU',
    appId: '1:815327431922:android:a9f0c727b619c47df4546b',
    messagingSenderId: '815327431922',
    projectId: 'mobile-doctors-5dea5',
    storageBucket: 'mobile-doctors-5dea5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJo3aQ2GOzYmgQoH8UCA3XVKTiv-WgUOg',
    appId: '1:815327431922:ios:3a96366aa8dc9883f4546b',
    messagingSenderId: '815327431922',
    projectId: 'mobile-doctors-5dea5',
    storageBucket: 'mobile-doctors-5dea5.appspot.com',
    androidClientId:
        '815327431922-8dfdn5v4f6lj7312et5rv9t1qovtq2gm.apps.googleusercontent.com',
    iosClientId:
        '815327431922-5v4gkeu3cblns26be29q4902qme9n7k7.apps.googleusercontent.com',
    iosBundleId: 'com.yarisa.healthcare',
  );
}
